version: '3.3'
services:
  postgredb:
    container_name: postgredb
    hostname: postgredb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd123321
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  daw_server-service-1:
    container_name: daw_server-service-1
    hostname: daw_server-service-1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=abcd123321"
      PORT: 8080
    ports:
      - 8080:8080
